### PR TITLE
Truncate desc

### PR DESCRIPTION
**Pull request by wsf246**
Truncates list description for list index

### CODE REVIEW

**Comment by briankung** [comment]
Does this truncate on word boundaries?

**Comment by wsf246** [comment]
No, just by characters length.

**Comment by briankung** [comment]
We can do that like so: http://stackoverflow.com/a/8714220/1042144

(I would use Ruby 1.9 syntax for the hash, of course)

**Comment by wsf246** [comment]
done, let me know if there's anything else.

**Pull request merged**
