### PR TITLE
Full width autocomplete

### PR DESCRIPTION
**Pull request by wsf246**
**Problem:**
autocomplete wasn't pulled across the whole input width
**Solution:**
use left and right to pull all the way across.

### CODE REVIEW

**Comment by briankung** [comment]
I'm confused how this works. Also, it's not actually padding

**Comment by briankung** [comment]
I see, so it just sets the left and right boundaries to be the same as its sibling input

**Comment by briankung** [comment]
On one hand, at least the tags in the search results wraps. On the other hand, I discovered this: 
screen shot 2017-01-10 at 12 30 22 pm

**Comment by wsf246** [comment]
I think heroku is imploding:
image

**Comment by wsf246** [comment]
when did this happen?
image

weird

**Comment by briankung** [comment]
I mad that tag really long to see if it would overflow the search result container

**Comment by briankung** [comment]
It doesn't overflow the search result container, but it does overflow the card, and I can't seem to figure out how to constrain it for whatever reason

**Comment by briankung** [comment]
This is with the following css:

```css
a.btn {
  width: 200px;
  text-overflow: ellipsis;
  white-space: nowrap;
}
```
screen shot 2017-01-10 at 12 36 46 pm

**Comment by wsf246** [comment]
We should probably limit tag char lengths.

**Comment by briankung** [comment]
We should also have a CSS solution.

**Comment by briankung** [comment]
Anyway, I'm gonna merge this

**Pull request merged**
