### PR TITLE
Deactive deleted user's comments

### PR DESCRIPTION
**Pull request by emarcha**
**Note:** Submitting this for initial review before continuing to work on the remaining bugs listed in #8 

**Problem:**
Deleted user's comments were causing a null-pointer exception

**Solution:**
Only display a comment if it has an active userId; display error message otherwise. 

**Complications:**
N/A

**Feature Changelog:**
Resolves the first part of #8 

- Add check on user attribute of each comment before rendering

### CODE REVIEW

**Comment by briankung** [comment]
Whoa, a wild pull request appeared! Thanks, Manny!

So what we've got in this PR looks like:

screen shot 2016-12-09 at 7 21 13 pm
Which becomes:
screen shot 2016-12-09 at 7 21 57 pm

You couldn't possibly know this, but comments might be width-constrained very soon in the future, so I was thinking it might be nice to follow reddit's lead with the "deleted" messages and just display "[deleted]" and keep the comment content. Just like reddit, as seen below:

screen shot 2016-12-09 at 7 31 59 pm

We probably want to keep the copy close to the same "Added by [deleted] on..."

**Comment by emarcha** [comment]
Alright! It now displays like this: 

screen shot 2016-12-11 at 1 49 26 pm

**Comment by briankung** [comment]
@emarcha looks good to me! Do you want to keep working on this branch, or should I merge?

**Comment by emarcha** [comment]
@briankung let's go ahead and merge. I'll open up new individual issues for the remaining bugs documented in #8. Thanks!

**Comment by wsf246** [comment]
:+1:

**Comment by briankung** [comment]
Should be live at https://afternoon-meadow-22528-staging.herokuapp.com shortly. PS, feel free to join us on gitter for chat at https://gitter.im/projectcredo/Lobby

**Pull request merged**
